### ISSUE TITLE
Feature Request: Collaborate with Istio-Operator

### ISSUE THREAD

**Issue by StevenACoffman** [istio-ecosystem/istio-installer#10]
Please consider collaboration with the banzaicloud [istio-operator](https://github.com/banzaicloud/istio-operator) which has very similar goals for piece meal installation and upgrade of istio and it's dependencies, but also has aspirations towards management of operating istio.

The goal of the Istio-operator is to automate and simplify these and enable popular service mesh use cases (multi cluster federation, canary releases, resource reconciliation, etc) by introducing easy higher level abstractions.

For our selfish use case, we would like to use the prometheus operator with istio and be able to upgrade and manage them separately. Ideally other pieces would similarly managed by an operator.

Please see parallel request banzaicloud/istio-operator#150

**Comment by sdake** [comment]
@StevenACoffman this repository will not (AFAIK) contain the operator itself.  We have not decided as a project where the operator should go.

It makes complete sense to unify on one operator implementation for Istio.  At the moment, this work is done from the environments working group.  The fundamental issue that we are dealing with is there are 3 or 4 different implementations.

I propose everyone **throw out** their current implementations of the operator specifically (this code base is what the operator would run against and would remain) and we start from a fresh repository from first principles for the go-based implementation.    There is considerable energy being consumed by implementing 4 parallel implementations when one implementation can meet everyone's needs.  Parallel implementations of installation technology don't lead to good outcomes if the goals and objectives are the same and there is no significant differentiating feature set.

cc / @costinm @knrc @StevenACoffman @sdake 

Please consider the above proposal and leave your thoughts.  I'd also encourage folks involved int his effort to *please* write down the `WHYS` of the operator work.  To get to why you have to go through how.  As a lot of folks have gone through how already, understanding and recording the `WHYS` should be easy.

I leave a diagram for folks to chew on related to the convergence of implementations into one implementation.  The easiest answer is to start over.

<img width="898" alt="Screen Shot 2019-03-29 at 1 35 10 AM" src="https://user-images.githubusercontent.com/755849/55219773-ffe1bc80-51c2-11e9-9759-eeeadb68d26f.png">

Cheers
-steve

**Comment by costinm** [comment]
I think it's great to have options, and I would be happy to see changes in istio-installer to better align with other projects. Istio goal is to run in multiple environments ('everywhere' if possible), and support multiple deployment and management styles. 

The goal of this project is to modularize the current installer so it is easier to integrate into operators or other tools ( CI/CD, etc). 

There is a separate bug about prometheus operator - as I commented there if it is possible to automate the setup of prom operator, with our additional configs, I would be happy to see it merged and I don't 
mind removing the current istio-specific prometheus template. Same for grafana, zipkin and all other external deps.

**Comment by costinm** [comment]
There is a separate issue for 'prometheus' - and I'm trying to minimize bugs opened for long term, we can move this to a docs/ folder and state the intentions or plans.
