### ISSUE TITLE
use case: third party CRDs should be separated from the main CRD file

### ISSUE THREAD

**Issue by sdake** [istio-ecosystem/istio-installer#14]
An example that has been raised in the past is that Istio - while integrating with certmanager already existing in the cluster, should not create or modify certmanager's CRDs.

This can be taken to the natural conclusion that any third party addon that introduces CRDs should have their CRD files stored in a separate file and applied independently.

**Comment by costinm** [comment]
How about:
- create a folder /crds
- separate the files, as you suggest
- user and test scripts can use "kubectl apply -d crds"
- advanced user can apply them independetly
